services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: rng-seed
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./screate.sql:/docker-entrypoint-initdb.d/create.sql
volumes:
  mysql_data:
    name: mysql_data
